title: Kelvio Silva
description: Web Developer / Cybersecurity / IT Infrastructure
#Alterado de download_links para show_links
show_links: true
google_analytics:
theme: jekyll-theme-dinky
#Criado a variável
github: 
      linkedin: https://www.linkedin.com/in/kelvio-silva
      owner_url: https://github.com/KWWS
      repository_url: https://github.com/KWWS/dinky
